# Generated by Django 3.2.4 on 2021-08-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('descrição', models.TextField()),
                ('foto', models.FileField(upload_to='media/%y/%m/%d/')),
            ],
        ),
    ]
